import common from './common';
import article from './article';
import comment from './comment';
import thumb from './thumb';
import oauth from './oauth';
import user from './user';
import say from './say';
import config from './config';
import daka from './daka';
import rule from './rule';

export const userSchema = { ...common, ...user };
export const oauthSchema = { ...common, ...oauth };
export const articleSchema = { ...common, ...article };
export const commentSchema = { ...common, ...comment };
export const thumbSchema = { ...common, ...thumb };
export const saySchema = { ...common, ...say };
export const configSchema = { ...common, ...config };
export const dakaSchema = { ...common, ...daka };
export const ruleSchema = { ...common, ...rule };
